# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FastWay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FastWay


# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

#Google map pods

  pod 'GoogleMaps', '4.1.0'
  pod 'GooglePlaces', '4.1.0'

end
